Updating with a new restricted_user role
balena-io/open-balena-api pull request #655
Opened 2021-05-02 10:51 UTC by nitishagar

First usage with email verification: https://github.com/balena-io/balena-api/pull/2913

Change-Type: minor

2021-05-03 13:15 UTC, dfunckt requested changes
There's no point declaring a role here that is not used by the core API -- unless there's use for it, it should be defined in the cloud API.

2021-05-13 16:12 UTC, dfunckt commented on src/features/auth/hooks/assign-user-role.ts
> +				name: getNewUserRoleName() || 'default-user',
It's impossible for `getNewUserRoleName()` to return a null-ish value, so:

```suggestion
				name: getNewUserRoleName(),
```

2021-06-08 10:50 UTC, thgreasi commented on src/infra/auth/auth.ts
> +	getNewUserRole && getNewUserRole(user);
```suggestion
export let getNewUserRole: ((user: AnyObject) => string) = () => 'default-user';

export const setRegistrationRoleFunc = (
	registerFunc: (user: AnyObject) => string,
) => {
	getNewUserRole = registerFunc;
};
```

2021-06-08 10:55 UTC, thgreasi reviewed
And with that ^ and Akis' comments fixed, LGTM.
Not convinced I like the new name of `assign-default-user-role.ts`, since this is still the code that assigns the default registration role, regardless of what the role provider returns.

2021-06-08 10:59 UTC, thgreasi reviewed
LGTM

2021-06-08 10:59 UTC, thgreasi commented on src/infra/auth/auth.ts
> +export const getRegistrationRole = (user: AnyObject) => getNewUserRole(user);
I guess that's just so that no-one else can modify `getNewUserRole` right?

2021-06-08 11:15 UTC, dfunckt reviewed
Great stuff! My comment is optional, feel free to ignore.

2021-06-08 11:15 UTC, dfunckt commented on src/index.ts
> +	getNewUserRole?: (user: AnyObject) => string;
As per `GetUrlFunction` and `SetupFunction` above, let's give the callback a name that can be imported by clients:

```ts
  // src/infra/auth/auth.ts
  export type GetNewUserRoleFunction = (user: AnyObject) => string;
  
  // this file:
  getNewUserRole?: GetNewUserRoleFunction;
```

2021-06-08 11:44 UTC, Page- commented on src/infra/auth/auth.ts
> +import { AnyObject } from 'pinejs-client-core';
This is unnecessary - it's globally available
```suggestion
```

2021-06-08 11:44 UTC, Page- commented on src/infra/auth/auth.ts
> +	registerFunc: (user: AnyObject) => string,
```suggestion
	registerFunc: typeof getNewUserRole,
```

2021-06-08 11:44 UTC, Page- commented on src/infra/auth/auth.ts
> +export const getRegistrationRole = (user: AnyObject) => getNewUserRole(user);
I think you can inherit types like:
```suggestion
export const getRegistrationRole: typeof getNewUserRole = (user) => getNewUserRole(user);
```

2021-06-08 13:03 UTC, dfunckt approved these changes

2021-06-08 13:04 UTC, merged